---
title: "Class 17: Analyzing Sequencing Data in Cloud"
author: "Jervic Aquino (PID:A17756721)"
toc: TRUE
date: 03-04-2026
format: pdf
---

## Downstream Analysis

```{r}
library(tximport)

folders <- dir(pattern="SRR21568*")
samples <- sub("_quant", "", folders)
files <- file.path(folders, "abundance.h5")
names(files) <- samples
txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
```

```{r}
head(txi.kallisto$counts)
```

```{r}
colSums(txi.kallisto$counts)
```

```{r}
sum(rowSums(txi.kallisto$counts)>0)
```

```{r}
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]
keep2 <- apply(kset.nonzero,1,sd)>0
x <- kset.nonzero[keep2,]
```


## PCA

```{r}
pca <- prcomp(t(x), scale=TRUE)
summary(pca)
```



```{r}
plot(pca$x[,1], pca$x[,2],
     col=c("blue","blue","red","red"),
     xlab="PC1", ylab="PC2", pch=16)
```




```{r}
library(ggplot2)
```




> Q. Use ggplot to make a similar figure of PC1 and PC2

```{r}
ggplot(pca$x) +
  aes(PC1, PC2) +
  geom_point(col=c("blue","blue","red","red"))
```






> Q. a separate figure PC1 vs PC3

```{r}
ggplot(pca$x) +
  aes(PC1, PC3) +
  geom_point(col=c("blue","blue","red","red"))
```






> Q. and PC2 vs PC3

```{r}
ggplot(pca$x) +
  aes(PC2, PC3) +
  geom_point(col=c("blue","blue","red","red"))
```

